<#
.SYNOPSIS
    Get registry rules where **ONLY** equality test is done.
#>
function Get-Outlook2010Registry {
    [CmdletBinding()]
    param()

    @{
        'SV-33513r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\pubcal', 'RestrictedAccessOnly', '1')
        'SV-33524r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'EnableRememberPwd', '0')
        'SV-33515r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\pubcal', 'DisableOfficeOnline', '1')
        'SV-33486r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'AuthenticationService', '9')
        'SV-33506r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'Hangup after Spool', '1')
        'SV-33857r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'EnableDEP', '1')
        'SV-33580r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'ShowLevel1Attach', '0')
        'SV-34109r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'NoCheckOnSessionSecurity', '1')
        'SV-33548r2_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\Outlook\Options\Mail', 'BlockExtContent', '0')
        'SV-33519r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'ReadSignedAsPlain', '1')
        'SV-33568r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'RespondToReceiptRequests', '2')
        'SV-33507r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'Warn on Dialup', '1')
        'SV-33594r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMMeetingTaskRequestResponse', '0')
        'SV-33522r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'JunkMailTrustContacts', '1')
        'SV-33597r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'JunkMailEnableLinks', '0')
        'SV-33588r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMAddressBookAccess', '0')
        'SV-34103r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'Message RTF Format', '1')
        'SV-33511r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'SharedFolderScript', '0')
        'SV-33521r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook', 'DisableAntiSpam', '0')
        'SV-34106r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'ForceDefaultProfile', '0')
        'SV-33571r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'WarnAboutInvalid', '1')
        'SV-33496r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\webcal', 'EnableAttachments', '0')
        'SV-33563r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'MsgFormats', '1')
        'SV-33525r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook', 'DisallowAttachmentCustomization', '1')
        'SV-33501r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\rss', 'SyncToSysCFL', '0')
        'SV-33932r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'AddinTrust', '1')
        'SV-33561r2_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'Internet', '0')
        'SV-33520r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'JunkMailTrustOutgoingRecipients', '0')
        'SV-33565r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'FIPSMode', '1')
        'SV-33514r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\pubcal', 'DisableDav', '1')
        'SV-34101r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\rss', 'EnableAttachments', '0')
        'SV-33529r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'UnblockSpecificSenders', '0')
        'SV-33510r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PublicFolderScript', '0')
        'SV-33577r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'AdminSecurityMode', '3')
        'SV-33570r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'ClearSign', '1')
        'SV-33487r2_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\autodiscover', 'ZeroConfigExchange', '1')
        'SV-34107r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'MinEncKey', '168')
        'SV-33516r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\pubcal', 'PublishCalendarDetailsPolicy', [regex]'^(?:4000|16384)$')
        'SV-33493r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\rpc', 'EnableRPCEncryption', '1')
        'SV-33574r2_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'SigStatusNoTrustDecision', '2')
        'SV-33499r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\webcal', 'Disable', '1')
        'SV-33595r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMSend', '0')
        'SV-34110r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'SupressNameChecks', '1')
        'SV-33589r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMFormulaAccess', '0')
        'SV-33509r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'NonDefaultStoreScript', '0')
        'SV-33500r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\rss', 'EnableFullTextHTML', '0')
        'SV-33540r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'TrustedZone', '0')
        'SV-33598r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'Level', '2')
        'SV-33503r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\meetings\profile', 'ServerUI', '2')
        'SV-33504r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\common\mailsettings', 'DisableSignatures', '0')
        'SV-33508r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\general', 'Check Default Client', '1')
        'SV-33512r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\general', 'MSGFormat', '0')
        'SV-33523r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'AllowActiveXOneOffForms', '0')
        'SV-33558r2_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'UnblockSafeZone', '1')
        'SV-33562r2_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'Intranet', '0')
        'SV-33593r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMAddressInformationAccess', '0')
        'SV-33880r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'UseCRLChasing', '1')
        'SV-33592r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMSaveAs', '0')
        'SV-33587r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'PromptOOMCustomAction', '0')
        'SV-33586r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'EnableOneOffFormScripts', '0')
        'SV-33566r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'ExternalSMime', '0')
        'SV-33578r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'AllowUsersToLowerAttachments', '0')
        'SV-33517r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\pubcal', 'SingleUploadOnly', '1')
        'SV-33581r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'DontPromptLevel1AttachClose', '0')
        'SV-34105r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'EditorPreference', '65536')
        'SV-33582r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\security', 'DontPromptLevel1AttachSend', '0')
        # rule is written back-a$$ward
        'SV-55984r2_rule' = @('HKCU:\software\policies\Microsoft\office\14.0\outlook\options\autoformat', 'pgrfafo_25_1', '0')
        'SV-33518r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\mail', 'ReadAsPlain', '1')
        # verified w/IA
        'SV-33502r1_rule' = @('HKCU:\Software\Policies\Microsoft\Office\14.0\outlook\options\rss', 'Disable', '0')
    };
}